# .github/workflows/build-and-push.yml
name: CI - Build and Push Container to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: burnished-net-469105-s2
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: sentiment-analysis-repo
  IMAGE_NAME: sentiment-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        # CORRECTED POOL NAME HERE
        workload_identity_provider: 'projects/958522348587/locations/global/workloadIdentityPools/github-pool-main/providers/github-provider'
        service_account: 'sentiment-analysis-api@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Docker auth
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev -q

    - name: Build and push Docker image
      run: |
        IMAGE_URI="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
        docker build -t $IMAGE_URI:${{ github.sha }} .
        docker push $IMAGE_URI:${{ github.sha }}