name: CD - Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI - Build and Push Container"]
    types:
      - completed

jobs:
  deploy:
    # Only run this job if the CI workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Get latest image URI from GHCR
      id: get-image
      run: |
        # Construct the full image name, forcing it to lowercase
        IMAGE_URI="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):$(echo ${{ github.event.workflow_run.head_sha }})"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: sentiment-api-service # This will be the name of your service
        region: us-central1 # You can change this to your preferred region
        image: ${{ steps.get-image.outputs.IMAGE_URI }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # This flag makes your API public so you can test it
        flags: '--allow-unauthenticated'
        
    - name: Show Deployed URL
      run: |
        echo "Deployment successful! URL: ${{ steps.deploy.outputs.url }}"